{{- if .Values.logging.promtail.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "plex.fullname" . }}-promtail
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "plex.name" . }}
    helm.sh/chart: {{ include "plex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
    positions:
      filename: /tmp/positions.yaml
    clients:
    - url: {{ .Values.logging.promtail.loki.url }}
    scrape_configs:
    - job_name: plex-logs
      static_configs:
      - targets:
          - localhost
        labels:
          job: plex-logs
          __path__: "/plex-logs/*.log"
    - job_name: plex-plugin-logs
      static_configs:
      - targets:
          - localhost
        labels:
          job: plex-plugin-logs
          __path__: "/plex-logs/PMS Plugin Logs/*.log"
{{- end }}
